
---
deployment:
  replicaCount: 2
  image:
    name: rommell/simple-go-app
    version: latest
  listenPort: 8080

serviceAccount:
  name: simple-go-app-sa
  annotations:
    eks.amazonaws.com/role-arn: PLACEHOLDER

dynamodbTableName: PLACEHOLDER
